CREATE TABLE IF NOT EXISTS outboxpro_outbox (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    event_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(200) NOT NULL,
    schema_version VARCHAR(50) NOT NULL,
    producer VARCHAR(200) NOT NULL,
    exchange_name VARCHAR(255) NOT NULL,
    routing_key VARCHAR(255) NOT NULL,
    payload_json JSON NOT NULL,
    trace_id VARCHAR(128),
    correlation_id VARCHAR(128),
    causation_id VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    next_retry_time DATETIME(6),
    claim_owner VARCHAR(100),
    claimed_time DATETIME(6),
    last_error_type VARCHAR(300),
    last_error_message VARCHAR(2000),
    created_time DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    sent_time DATETIME(6),
    updated_time DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_outbox_event_id (event_id),
    KEY idx_outbox_pending (status, next_retry_time, id),
    KEY idx_outbox_claim (status, claimed_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS outboxpro_inbox (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    consumer_name VARCHAR(200) NOT NULL,
    event_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(200) NOT NULL,
    status VARCHAR(32) NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    last_error VARCHAR(2000),
    received_time DATETIME(6) NOT NULL,
    processed_time DATETIME(6),
    updated_time DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_consumer_event (consumer_name, event_id),
    KEY idx_inbox_status (consumer_name, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS outboxpro_message_log (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    event_id VARCHAR(100) NOT NULL,
    message_id VARCHAR(100),
    event_type VARCHAR(200) NOT NULL,
    trace_id VARCHAR(128),
    correlation_id VARCHAR(128),
    causation_id VARCHAR(128),
    producer VARCHAR(200),
    consumer VARCHAR(200),
    exchange_name VARCHAR(255),
    queue_name VARCHAR(255),
    routing_key VARCHAR(255),
    stage VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    attempt INT NOT NULL DEFAULT 1,
    duration_ms BIGINT,
    error_type VARCHAR(300),
    error_message VARCHAR(2000),
    occurred_time DATETIME(6) NOT NULL,
    KEY idx_message_event (event_id),
    KEY idx_message_trace (trace_id),
    KEY idx_message_time (occurred_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
